# Generated by Django 3.2.18 on 2023-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('container_id', models.IntegerField(primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=10)),
                ('container_status', models.CharField(choices=[('E', 'Empty'), ('L', 'laden')], default='E', max_length=10)),
                ('container_size', models.IntegerField()),
                ('cargo', models.CharField(choices=[('E', 'Empty'), ('L', 'laden')], default='D', max_length=20)),
            ],
        ),
    ]
