# Generated by Django 3.2.18 on 2023-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='cargo',
            field=models.CharField(choices=[('D', 'Dry goods'), ('H', 'Hazardous materials'), ('L', 'Liquid cargo')], default='D', max_length=20),
        ),
    ]
