# Generated by Django 4.1.7 on 2023-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_container_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_name',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_size',
            field=models.IntegerField(choices=[('20', '20'), ('40', '40')], default='40'),
        ),
    ]
