# Generated by Django 3.2.18 on 2023-03-01 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_container_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='time',
        ),
        migrations.AddField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
